/**
 * AUTO-GENERATED by notebook/gemma_rescue_grid_kaggle.ipynb
 *
 * Scenario: Compound flood + electrical fires
 * Source:   8 EdgeTriageReports over a 60 minute window
 * Model:    /kaggle/input/models/google/gemma-4/transformers/gemma-4-31b-it/1 (4-bit via Unsloth)
 * Wall:     859.9s on Kaggle 2× T4
 * Run at:   2026-05-17T15:00:42Z
 *
 * Drop-in for dashboard/src/lib/. Imported by scenarios.ts and rendered
 * by FloodSynthesisPanel.
 */

import type { CommandCenterSynthesis } from "./types";

export const scenarioCSynthesis: CommandCenterSynthesis = {
  "incident_id": "c3f0e4d6-0001-4a9b-9c45-synthesis-20260420",
  "synthesis_timestamp_iso": "2026-04-20T17:05:00Z",
  "report_count": 8,
  "time_window": {
    "start_iso": "2026-04-20T16:05:00Z",
    "end_iso": "2026-04-20T16:58:00Z"
  },
  "primary_disaster_classification": {
    "type": "flood",
    "confidence": 0.85,
    "secondary_types": [
      "fire",
      "building_collapse"
    ]
  },
  "geographic_scope": "Jl. Industri III and Jl. Pemuda intersection area, specifically centered around Transformer 4B and Pak Hadi welding workshop.",
  "severity_distribution": {
    "1": 0,
    "2": 0,
    "3": 2,
    "4": 4,
    "5": 2
  },
  "estimated_affected": {
    "people_count_min": 25,
    "people_count_max": 35,
    "method": "Summation of visible persons across distinct locations, accounting for overlap in transformer/workshop zones."
  },
  "priority_zones": [
    {
      "label": "Pak Hadi Welding Workshop (Jl. Industri III no 17)",
      "max_severity": 5,
      "report_ids": [
        "c3f0e4d6-0003-4a9b-9c45-works-1620",
        "c3f0e4d6-0006-4a9b-9c45-works-1642"
      ],
      "evacuation_priority": "immediate",
      "dominant_hazards": [
        "petroleum fire",
        "drum rupture",
        "fire propagation on water"
      ],
      "rationale": "Highest severity; fuel-driven fire spreading via floodwater; one burn casualty extracted; imminent risk to adjacent units."
    },
    {
      "label": "Jl. Industri III / Jl. Pemuda Intersection",
      "max_severity": 4,
      "report_ids": [
        "c3f0e4d6-0005-4a9b-9c45-indus-1635"
      ],
      "evacuation_priority": "immediate",
      "dominant_hazards": [
        "fast-moving waist-deep water",
        "floating burning debris",
        "stranded emergency personnel"
      ],
      "rationale": "Critical rescue needed for two trapped paramedics on a stranded ambulance; high risk from floating fire."
    },
    {
      "label": "Transformer 4B Area",
      "max_severity": 4,
      "report_ids": [
        "c3f0e4d6-0001-4a9b-9c45-trans-1605",
        "c3f0e4d6-0002-4a9b-9c45-indus-1612",
        "c3f0e4d6-0004-4a9b-9c45-trans-1628"
      ],
      "evacuation_priority": "immediate",
      "dominant_hazards": [
        "electrical fire",
        "live electrical equipment in floodwater",
        "structural collapse"
      ],
      "rationale": "Compound hazard of live electricity and floodwater; partial collapse of lean-to structure."
    },
    {
      "label": "Warehouse Rooftop",
      "max_severity": 4,
      "report_ids": [
        "c3f0e4d6-0007-4a9b-9c45-rooft-1650"
      ],
      "evacuation_priority": "urgent",
      "dominant_hazards": [
        "stranded personnel",
        "exposure",
        "burning debris in water below"
      ],
      "rationale": "12 people stranded, including one distressed elderly individual; no ground exit available."
    }
  ],
  "consolidated_hazards": [
    {
      "hazard": "Compound Flood-Fire (Floating Petroleum)",
      "report_count": 4,
      "severity_implication": "Extremely high; fire is propagating across the water surface, bypassing traditional firebreaks."
    },
    {
      "hazard": "Electrical Hazard in Water",
      "report_count": 3,
      "severity_implication": "Lethal risk to responders and civilians wading in floodwater near Transformer 4B."
    },
    {
      "hazard": "Structural Collapse",
      "report_count": 1,
      "severity_implication": "Moderate; potential for trapped victims under debris at the transformer site."
    }
  ],
  "vulnerable_groups_summary": "One burn casualty extracted from workshop; one distressed elderly person stranded on warehouse rooftop; two paramedics trapped on vehicle roof.",
  "recommended_actions": [
    {
      "action": "Immediate boat/rope rescue of paramedics at Jl. Industri III/Jl. Pemuda intersection.",
      "priority": 1,
      "rationale": "Life safety of first responders; critical intersection blockage.",
      "responsible_party": "Water Rescue Team"
    },
    {
      "action": "Deploy foam suppressants to Pak Hadi workshop and adjacent units east.",
      "priority": 1,
      "rationale": "Petroleum fire on water cannot be fought with water; prevents further spread.",
      "responsible_party": "Fire Department (HazMat)"
    },
    {
      "action": "Emergency electrical isolation of Transformer 4B.",
      "priority": 1,
      "rationale": "Prevents electrocution of victims and responders in floodwater.",
      "responsible_party": "Electrical Utility Provider"
    },
    {
      "action": "Aerial or boat extraction of 12 persons from warehouse rooftop.",
      "priority": 2,
      "rationale": "Stranded group with elderly member; exposure risk.",
      "responsible_party": "Search and Rescue (SAR)"
    }
  ],
  "report_validity_notes": [
    {
      "report_id": "c3f0e4d6-0004-4a9b-9c45-trans-1628",
      "flag": "low_quality",
      "rationale": "Low confidence (0.58) due to smoke/rain obscuring image; building collapse inferred but not confirmed."
    },
    {
      "report_id": "c3f0e4d6-0002-4a9b-9c45-indus-1612",
      "flag": "conflicting",
      "rationale": "Classified as flood while report 0001 (same area) classified as fire; resolved as compound disaster."
    },
    {
      "report_id": "c3f0e4d6-0006-4a9b-9c45-works-1642",
      "flag": "verified_by_corroboration",
      "rationale": "Corroborates and updates the severity of report 0003 regarding the welding workshop."
    }
  ],
  "data_confidence_notes": "High confidence in the existence of a compound flood/fire event. Confidence is lower regarding the 'building collapse' at the transformer site due to poor image quality in report 0004. People counts are estimates based on visual reports and may fluctuate. Confidence would be improved by drone thermal imaging of the transformer lean-to and rooftop."
};
