/**
 * AUTO-GENERATED by notebook/gemma_rescue_grid_kaggle.ipynb
 *
 * Scenario: Shallow earthquake
 * Source:   15 EdgeTriageReports over a 120 minute window
 * Model:    /kaggle/input/models/google/gemma-4/transformers/gemma-4-31b-it/1 (4-bit via Unsloth)
 * Wall:     1106.2s on Kaggle 2× T4
 * Run at:   2026-05-17T15:00:42Z
 *
 * Drop-in for dashboard/src/lib/. Imported by scenarios.ts and rendered
 * by FloodSynthesisPanel.
 */

import type { CommandCenterSynthesis } from "./types";

export const scenarioBSynthesis: CommandCenterSynthesis = {
  "incident_id": "b2e9d3c5-0000-4f7a-8b34-earthquake-2026",
  "synthesis_timestamp_iso": "2026-04-19T10:30:00Z",
  "report_count": 15,
  "time_window": {
    "start_iso": "2026-04-19T08:15:00Z",
    "end_iso": "2026-04-19T10:12:00Z"
  },
  "primary_disaster_classification": {
    "type": "earthquake",
    "confidence": 0.95,
    "secondary_types": [
      "landslide"
    ]
  },
  "geographic_scope": "Cugenang, Sukaresmi, Mande, Pasirhayam, Gadog, Warungkondang, Pacet, Cipanas, and Bojongpicung areas. Impact spans residential, educational, religious, and medical infrastructure.",
  "severity_distribution": {
    "1": 0,
    "2": 3,
    "3": 4,
    "4": 5,
    "5": 3
  },
  "estimated_affected": {
    "people_count_min": 110,
    "people_count_max": 150,
    "method": "Summation of visible persons in shelters and schools, plus estimated residents in damaged residential rows."
  },
  "priority_zones": [
    {
      "label": "Sukaresmi Mosque & Adjacent House",
      "max_severity": 5,
      "report_ids": [
        "b2e9d3c5-0005-4f7a-8b34-sukar-0855",
        "b2e9d3c5-0012-4f7a-8b34-sukar-0944"
      ],
      "evacuation_priority": "immediate",
      "dominant_hazards": [
        "structural collapse",
        "trapped persons",
        "secondary collapse"
      ],
      "rationale": "Mass casualty site with confirmed entrapments and a secondary collapse of a minaret onto a residential structure."
    },
    {
      "label": "Cugenang Village Center",
      "max_severity": 5,
      "report_ids": [
        "b2e9d3c5-0001-4f7a-8b34-cugen-0815",
        "b2e9d3c5-0004-4f7a-8b34-cugen-0848",
        "b2e9d3c5-0015-4f7a-8b34-cugen-1012"
      ],
      "evacuation_priority": "immediate",
      "dominant_hazards": [
        "pancake collapse",
        "trapped person",
        "structural instability"
      ],
      "rationale": "Confirmed live victim under rubble; fire previously active but now suppressed. High-stakes extraction in progress."
    },
    {
      "label": "Warungkondang Clinic",
      "max_severity": 4,
      "report_ids": [
        "b2e9d3c5-0010-4f7a-8b34-warun-0930"
      ],
      "evacuation_priority": "immediate",
      "dominant_hazards": [
        "structural shifting",
        "patient evacuation"
      ],
      "rationale": "Medical facility compromised; critical need for patient transfer and stretcher assistance."
    },
    {
      "label": "Mande School",
      "max_severity": 4,
      "report_ids": [
        "b2e9d3c5-0003-4f7a-8b34-mande-0840",
        "b2e9d3c5-0009-4f7a-8b34-mande-0922"
      ],
      "evacuation_priority": "immediate",
      "dominant_hazards": [
        "roof collapse",
        "vulnerable population (children)"
      ],
      "rationale": "Large group of children present; active danger due to adult re-entering unstable classroom block."
    },
    {
      "label": "Gadog Highway KM 12",
      "max_severity": 4,
      "report_ids": [
        "b2e9d3c5-0006-4f7a-8b34-gadog-0902"
      ],
      "evacuation_priority": "urgent",
      "dominant_hazards": [
        "landslide",
        "buried vehicle",
        "slope instability"
      ],
      "rationale": "Critical transport artery blocked by quake-triggered landslide; potential for further slope failure."
    }
  ],
  "consolidated_hazards": [
    {
      "hazard": "Structural Collapse/Entrapment",
      "report_count": 6,
      "severity_implication": "Highest risk to life; requires heavy rescue and USAR teams."
    },
    {
      "hazard": "Gas Leaks (Propane/Gas Line)",
      "report_count": 3,
      "severity_implication": "High risk of fire/explosion in populated areas (Cugenang, Pacet)."
    },
    {
      "hazard": "Secondary Collapse/Aftershocks",
      "report_count": 8,
      "severity_implication": "Ongoing threat to rescuers and evacuees in damaged buildings."
    },
    {
      "hazard": "Landslide",
      "report_count": 1,
      "severity_implication": "Logistical blockage of primary highway; risk of burial."
    }
  ],
  "vulnerable_groups_summary": "High concentrations of children at Mande school (~30), elderly residents in Pasirhayam and Warungkondang clinic, and displaced persons at Bojongpicung community hall (~50).",
  "recommended_actions": [
    {
      "action": "Deploy Heavy USAR/Cranes to Sukaresmi and Cugenang",
      "priority": 1,
      "rationale": "Confirmed trapped persons and secondary structural collapses.",
      "responsible_party": "Heavy Rescue Task Force"
    },
    {
      "action": "Emergency Patient Transfer from Warungkondang Clinic",
      "priority": 1,
      "rationale": "Facility is structurally unsound; patients require stable medical environment.",
      "responsible_party": "EMS/Ambulance Corps"
    },
    {
      "action": "Immediate Evacuation of Mande School Block C",
      "priority": 1,
      "rationale": "Personnel reported inside unstable structure during aftershocks.",
      "responsible_party": "Field Triage Team"
    },
    {
      "action": "Hazmat Intervention at Pacet Market",
      "priority": 2,
      "rationale": "Audible gas leak in populated market area poses explosion risk.",
      "responsible_party": "Hazmat Unit"
    },
    {
      "action": "Highway Clearance and Slope Stabilization at Gadog KM 12",
      "priority": 2,
      "rationale": "Restore critical logistics artery and ensure safety of buried vehicle occupants.",
      "responsible_party": "Public Works/Geotech Team"
    }
  ],
  "report_validity_notes": [
    {
      "report_id": "b2e9d3c5-0004-4f7a-8b34-cugen-0848",
      "flag": "verified_by_corroboration",
      "rationale": "Corroborates and updates report 0001 regarding Cugenang site."
    },
    {
      "report_id": "b2e9d3c5-0012-4f7a-8b34-sukar-0944",
      "flag": "verified_by_corroboration",
      "rationale": "Corroborates and updates report 0005 regarding Sukaresmi site."
    },
    {
      "report_id": "b2e9d3c5-0015-4f7a-8b34-cugen-1012",
      "flag": "verified_by_corroboration",
      "rationale": "Final update for Cugenang site; confirms fire suppression."
    },
    {
      "report_id": "b2e9d3c5-0013-4f7a-8b34-cibeb-0952",
      "flag": "low_quality",
      "rationale": "Poor image quality due to rain; low confidence in disaster classification."
    }
  ],
  "data_confidence_notes": "High confidence in urban centers (Cugenang, Sukaresmi) due to multiple temporal reports. Confidence is lower in rural areas (Cibeber) due to poor image quality. People counts are inferred as minimums based on visible subjects in photographs; actual affected numbers are likely higher. Inferred that the landslide at Gadog was triggered by the earthquake based on temporal proximity."
};
