/**
 * AUTO-GENERATED by notebook/gemma_rescue_grid_kaggle.ipynb
 *
 * Scenario: Rapid-onset flood
 * Source:   12 EdgeTriageReports over a 90 minute window
 * Model:    /kaggle/input/models/google/gemma-4/transformers/gemma-4-31b-it/1 (4-bit via Unsloth)
 * Wall:     1036.0s on Kaggle 2× T4
 * Run at:   2026-05-17T15:00:42Z
 *
 * Drop-in for dashboard/src/lib/. Imported by scenarios.ts and rendered
 * by FloodSynthesisPanel.
 */

import type { CommandCenterSynthesis } from "./types";

export const scenarioASynthesis: CommandCenterSynthesis = {
  "incident_id": "a1f6c2d4-0001-4b8e-9c12-tegal3-1402",
  "synthesis_timestamp_iso": "2026-04-18T15:30:00Z",
  "report_count": 12,
  "time_window": {
    "start_iso": "2026-04-18T14:02:00Z",
    "end_iso": "2026-04-18T15:20:00Z"
  },
  "primary_disaster_classification": {
    "type": "flood",
    "confidence": 0.95,
    "secondary_types": []
  },
  "geographic_scope": "Central Jakarta area including Tegal Sari (Blocks 3, 5, 7), Manggarai Underpass/Station, Tebet Barat IV, and Cawang Junction.",
  "severity_distribution": {
    "1": 0,
    "2": 4,
    "3": 5,
    "4": 3,
    "5": 0
  },
  "estimated_affected": {
    "people_count_min": 15,
    "people_count_max": 25,
    "method": "Aggregation of visible persons across distinct geographic clusters, accounting for temporal overlap in Tegal Sari."
  },
  "priority_zones": [
    {
      "label": "Tegal Sari Block 5 (Jl. Tegal Sari V)",
      "max_severity": 4,
      "report_ids": [
        "a1f6c2d4-0003-4b8e-9c12-tegal5-1415",
        "a1f6c2d4-0004-4b8e-9c12-tegal5-1422",
        "a1f6c2d4-0010-4b8e-9c12-tegal5-1510"
      ],
      "evacuation_priority": "immediate",
      "dominant_hazards": [
        "downed live power line",
        "waist-high floodwater"
      ],
      "rationale": "High severity due to active electrical hazard in water and a trapped elderly resident (since extracted but site remains hazardous)."
    },
    {
      "label": "Manggarai Underpass / Station Plaza",
      "max_severity": 4,
      "report_ids": [
        "a1f6c2d4-0005-4b8e-9c12-mangg-1430",
        "a1f6c2d4-0008-4b8e-9c12-mangg-1450"
      ],
      "evacuation_priority": "immediate",
      "dominant_hazards": [
        "fully flooded underpass",
        "strong current",
        "submerged vehicle"
      ],
      "rationale": "Potential trapped rider in submerged vehicle and high concentration of stranded commuters including children and elderly."
    },
    {
      "label": "Tegal Sari Block 3 (RT 04/05)",
      "max_severity": 3,
      "report_ids": [
        "a1f6c2d4-0001-4b8e-9c12-tegal3-1402",
        "a1f6c2d4-0002-4b8e-9c12-tegal3-1408",
        "a1f6c2d4-0006-4b8e-9c12-tegal3-1435",
        "a1f6c2d4-0012-4b8e-9c12-tegal3-1520"
      ],
      "evacuation_priority": "urgent",
      "dominant_hazards": [
        "thigh-high floodwater",
        "sagging electrical wires"
      ],
      "rationale": "Consistent rising water trend over 90 minutes; reported minor injury and presence of children."
    },
    {
      "label": "Tegal Sari Block 7",
      "max_severity": 3,
      "report_ids": [
        "a1f6c2d4-0009-4b8e-9c12-tegal7-1501"
      ],
      "evacuation_priority": "urgent",
      "dominant_hazards": [
        "structural wall collapse",
        "strong current"
      ],
      "rationale": "Structural failure into floodwater creates debris flow risk for downstream areas."
    }
  ],
  "consolidated_hazards": [
    {
      "hazard": "Electrical/Power Lines",
      "report_count": 3,
      "severity_implication": "Critical life-safety risk; downed live lines in waist-high water in Block 5 and sagging lines in Block 3."
    },
    {
      "hazard": "Submerged Vehicles",
      "report_count": 3,
      "severity_implication": "High risk of trapped occupants, specifically in Manggarai Underpass."
    },
    {
      "hazard": "Structural Failure",
      "report_count": 1,
      "severity_implication": "Moderate risk; wall collapse in Block 7 may cause debris blockages or secondary collapses."
    }
  ],
  "vulnerable_groups_summary": "Elderly residents (one extracted from roof in Block 5, one stranded at Manggarai Station) and children (present at Manggarai Station and Block 3) are identified. One minor injury reported in Block 3.",
  "recommended_actions": [
    {
      "action": "Immediate power grid disconnect for Tegal Sari Block 5 and Block 3",
      "priority": 1,
      "rationale": "Prevent electrocution in waist-high floodwaters where live lines are confirmed.",
      "responsible_party": "Electrical Utility Provider"
    },
    {
      "action": "Search and Rescue (SAR) dive/boat operation at Manggarai Underpass",
      "priority": 1,
      "rationale": "Verify status of rider in submerged motorcycle in fully flooded underpass.",
      "responsible_party": "Emergency Rescue Services"
    },
    {
      "action": "Cordon and debris clearance at Tegal Sari Block 7",
      "priority": 3,
      "rationale": "Prevent residents from entering unstable collapsed wall area and manage debris flow.",
      "responsible_party": "Public Works / Local Police"
    },
    {
      "action": "Establish transit shuttle from Manggarai Station to dry zones",
      "priority": 3,
      "rationale": "Evacuate stranded commuters, including children and elderly, from the flooded plaza.",
      "responsible_party": "Transit Authority"
    }
  ],
  "report_validity_notes": [
    {
      "report_id": "a1f6c2d4-0010-4b8e-9c12-tegal5-1510",
      "flag": "verified_by_corroboration",
      "rationale": "Confirms and updates the high-severity situation reported in a1f6c2d4-0004."
    },
    {
      "report_id": "a1f6c2d4-0009-4b8e-9c12-tegal7-1501",
      "flag": "low_quality",
      "rationale": "Reported fair image quality due to rain; structural collapse needs physical verification."
    },
    {
      "report_id": "a1f6c2d4-0002-4b8e-9c12-tegal3-1408",
      "flag": "conflicting",
      "rationale": "Severity increased from 2 to 3 within 6 minutes at same location; resolved as a rising water trend."
    }
  ],
  "data_confidence_notes": "High confidence in flood classification and electrical hazards. Moderate confidence in the number of affected people due to overlapping reports in Tegal Sari. Inferred that the 'submerged motorcycle' in Manggarai Underpass may have a trapped rider based on the 'severity 4' rating and 'immediate action' request. Confidence would improve with drone overflights of Block 7 and the Underpass."
};
